CREATE TABLE USERS
(
  USER_ID                INT AUTO_INCREMENT
    PRIMARY KEY,
  USER_NAME              VARCHAR(30)  NOT NULL,
  PASSWORD               VARCHAR(255) NOT NULL,
  CREATION_DATE          DATE         NOT NULL,
  USER_TOKEN             VARCHAR(255) NULL,
  GLOBAL_PRIVACY_SETTING VARCHAR(1)   NULL,
  END_DATE               DATE         NULL,
  CONSTRAINT USERS_USER_NAME_uindex
  UNIQUE (USER_NAME)
);

CREATE TABLE PICTURES
(
  PICTURE_ID             INT AUTO_INCREMENT
    PRIMARY KEY,
  CREATION_DATE          DATE       NOT NULL,
  CONFIDENCE_IS_FOOD     FLOAT      NOT NULL,
  CONFIDENCE_IS_NOT_FOOD FLOAT      NOT NULL,
  PRIVATE                VARCHAR(1) NULL,
  END_DATE               DATE       NULL,
  USER_ID                INT        NULL,
  CONSTRAINT PICTURES_ibfk_1
  FOREIGN KEY (USER_ID) REFERENCES USERS (USER_ID)
);
CREATE INDEX USER_ID
  ON PICTURES (USER_ID);

CREATE TABLE FAVORITES
(
  FAVORITE_ID   INT AUTO_INCREMENT
    PRIMARY KEY,
  USER_ID       INT  NULL,
  PICTURE_ID    INT  NULL,
  CREATION_DATE DATE NULL,
  END_DATE      DATE NULL,
  CONSTRAINT FAVORITES_ibfk_2
  FOREIGN KEY (USER_ID) REFERENCES USERS (USER_ID),
  CONSTRAINT FAVORITES_ibfk_1
  FOREIGN KEY (PICTURE_ID) REFERENCES PICTURES (PICTURE_ID)
);
CREATE INDEX PICTURE_ID
  ON FAVORITES (PICTURE_ID);
CREATE INDEX USER_ID
  ON FAVORITES (USER_ID);
